### ISSUE TITLE
Error using put:  VFY: unable to resolve virtual method setFixedLengthStreamingMode

### ISSUE THREAD

**Issue by kehollin** [hgoebl/DavidWebb#1]
Here's a chunk of the logcat with the VFY warning and the actual error.

01-20 11:30:06.724: W/dalvikvm(22051): VFY: unable to resolve virtual method 6870: Ljava/net/HttpURLConnection;.setFixedLengthStreamingMode (J)V
01-20 11:30:16.825: W/dalvikvm(22051): threadid=16: thread exiting with uncaught exception (group=0x4172c438)
01-20 11:30:16.915: E/AndroidRuntime(22051): FATAL EXCEPTION: IntentService[BeWell24Sync]
01-20 11:30:16.915: E/AndroidRuntime(22051): java.lang.NoSuchMethodError: java.net.HttpURLConnection.setFixedLengthStreamingMode
01-20 11:30:16.915: E/AndroidRuntime(22051):    at com.goebl.david.WebbUtils.getPayloadAsBytesAndSetContentType(WebbUtils.java:237)
01-20 11:30:16.915: E/AndroidRuntime(22051):    at com.goebl.david.Webb.execute(Webb.java:238)
01-20 11:30:16.915: E/AndroidRuntime(22051):    at com.goebl.david.Request.asJsonObject(Request.java:217)
01-20 11:30:16.915: E/AndroidRuntime(22051):    at edu.asu.snhp.bewell24.comms.SynchronizerService.syncTable(SynchronizerService.java:84)

Interestingly there's a new version of this method in API 19 with a different signature, but sadly the logcat doesn't show the full method signature.  I have API 19 currently set as the target in my project's properties.

I'm a bit under the gun, so I wanted to post this early in case I'm doing something wrong that you can spot right away.  I'll update this issue if I get any different results.

**Comment by Deidresb** [comment]
Ok so dumb question but haven't done anything but reg software updates to my phone and it's giving me that same log up there what on Earth did I do

**Comment by hgoebl** [comment]
Sorry, I have no clue. Look into the history of your source code versioning system (Git?)
