### ISSUE TITLE
SocketTimeoutException on bad IP address

### ISSUE THREAD

**Issue by akmal** [hgoebl/DavidWebb#10]
Great library.
However, it does not advertize that a SocketTimeoutException will be thrown on bad IP address. Here is the stack trace:

W/System.err﹕ com.goebl.david.WebbException: java.net.SocketTimeoutException: failed to connect to /10.20.120.57 (port 8080) after 10000ms
09-23 15:57:33.065  24791-24813/com.vmware.bsky W/System.err﹕ at com.goebl.david.Webb.execute(Webb.java:329)
09-23 15:57:33.065  24791-24813/com.vmware.bsky W/System.err﹕ at com.goebl.david.Request.asJsonObject(Request.java:257)
09-23 15:57:33.065  24791-24813/com.vmware.bsky W/System.err﹕ at com.vmware.bsky.ConfigCheckActivity$Async.doInBackground(ConfigCheckActivity.java:90)
09-23 15:57:33.066  24791-24813/com.vmware.bsky W/System.err﹕ at com.vmware.bsky.ConfigCheckActivity$Async.doInBackground(ConfigCheckActivity.java:71)
09-23 15:57:33.066  24791-24813/com.vmware.bsky W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:292)
09-23 15:57:33.066  24791-24813/com.vmware.bsky W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by hgoebl** [comment]
As DavidWebb is really just a thin wrapper around HttpURLConnection, there is nothing I can do in this case. Try http://10.20.120.57/ in Chrome, there will be `ERR_CONNECTION_TIMED_OUT` after a while.

I suppose, you have to check against invalid IP-addresses for your own.
