### ISSUE TITLE
handling multiple values with identical parameter name

### ISSUE THREAD

**Issue by itaisanders** [hgoebl/DavidWebb#14]
http get requests support sending parameters with multiple values even though having identical keys.
in some cases, it is required by an external service api (in my case: [solr's fq parameter](https://wiki.apache.org/solr/CommonQueryParameters#fq) can be called multiple times in a single http call in order to define filtering a query by various fields).

implementing the parameters list as a Map restricts the request to hold only one value for each parameter value.

**Comment by hgoebl** [comment]
I'd suggest to handle this by using an array or a collection as the object. Example:

    request.param("name", ["cheese", "onions", "salami"])

This can be used in `request.params(Map<String, Object>)` as well.

Do you think this is a valid solution?
Or do you have other ideas?

**Comment by itaisanders** [comment]
idk. I suspect it might mess up with the api, but I'll test it on Sunday and let you know what I find.

**Comment by itaisanders** [comment]
I tried collecting my filters into a single array object and pass it under the fq parameter as suggested.
I don't know how it would work for other services, but solr takes it as a single string and since the brackets ([ ]) represent a ranged query in solr api and thus the entire request throws an exception for bad parsing.

**Comment by itaisanders** [comment]
posted a pull request with a quick fix for this issue.

**Comment by hgoebl** [comment]
Thanks, looks quite good to me. Unfortunately `javafx.util.Pair` is a bit too exotic for Android platform. Do you know of an alternative implementation? If not, I'd rather provide my own.

**Comment by itaisanders** [comment]
I use it for a pc application, so I just went with whatever worked.
if you have a more suitable solution for you needs - go a head and do it. it is your code after all ;)

**Comment by itaisanders** [comment]
how about if I use the Entry class, just like Map does only in a list?

**Comment by itaisanders** [comment]
I am sending you a very quick implementation of a Parameter class.
I figured that the use of it is very specific so there is no reason not to create a simple class to answer our needs here.
o/c it can be modified to answer more needs in the future if any arise.
