### ISSUE TITLE
Allow to get the result as InputStream

### ISSUE THREAD

**Issue by essobedo** [hgoebl/DavidWebb#18]
Up to now, all results are loaded into memory as a byte array which makes it unusable to get big content such as big files for example. Moreover allowing to access to the result as _InputStream_ allows the end user to use its own parser which is an open door to many new possibilities for the project.

**Comment by essobedo** [comment]
@hgoebl Please have a look to my ticket and the related PR https://github.com/hgoebl/DavidWebb/issues/19 and tell me what think about them.

**Comment by hgoebl** [comment]
Looks quite good to me. I'll have a closer look at it tomorrow, now I have to get my bread-and-butter work done.

**Comment by essobedo** [comment]
@hgoebl thank you for merging, any idea of when you plan to release 1.3?

**Comment by essobedo** [comment]
@hgoebl I can see that you are already doing the release so forget my question and thank you again

**Comment by hgoebl** [comment]
Many thanks @essobedo - very good work, perfectly crafted!

**Comment by essobedo** [comment]
@hgoebl you're welcome and thank you for your helpful project
