### ISSUE TITLE
Crashes after update UI

### ISSUE THREAD

**Issue by rcmcastro** [hgoebl/DavidWebb#21]
I liked your library because ti's too simple. But it runs on the main thread and you can not update the UI after get the response.

**Comment by hgoebl** [comment]
Not a bug. It runs on the thread where you start it.
Try to use `AsyncTask` or `IntentService` or your own Thread management.
Or you can use a higher-level library like Volley.

**Comment by rcmcastro** [comment]
I used AsyncTask. You library is easier than Volley

**Comment by hgoebl** [comment]
Thanks for contributing. I'm going to add documentation so everybody can see how to avoid doing I/O on Main-Thread.
