### ISSUE TITLE
it not support proxy?

### ISSUE THREAD

**Issue by cuicp** [hgoebl/DavidWebb#22]
it not support proxy?

**Comment by hgoebl** [comment]
Please have a look at following [StackOverflow answers](http://stackoverflow.com/q/1432961/2176962) and also at [this article](http://www.rgagnon.com/javadetails/java-0085.html).

If this is not enough or if an API change in DavidWebb is required, then please let me know. Of course you can also make a pull request :-)

**Comment by hgoebl** [comment]
I've updated current SNAPSHOT version 1.3.1.

You can now call:

``` java
Webb webb = Webb.create();
webb.setProxy(proxy);
webb.get(....)
```

see documentation of `java.net.URL.openConnection(proxy)` how to create a valid proxy object.
