### ISSUE TITLE
null ErrorStream when POST Request returns 401

### ISSUE THREAD

**Issue by dreske** [hgoebl/DavidWebb#8]
When I do a POST Request with a JSON Body, where the server (Jboss) returns a 401 Error, the error stream is null.

When commenting out `connection.setFixedLengthStreamingMode` (WebbUtils.java) the error stream returns the server response.

Any Idea, how to fix this issue?

**Comment by hgoebl** [comment]
Could you send the communication trace (what you post, what the server responds, e.g. with a verbose flag and a tool like `curl`)? I'd like to see how "standard" HTTP tools interact with your server.

BTW 401 is a quite standard error code which normally doesn't need an error response. An http header `WWW-Authenticate` header field containing a challenge applicable to the requested resource should be enough information for the client. Of course it's sometimes easier to deal with JSON error responses, I know...

**Comment by dreske** [comment]
Simple client code:
```java
JSONObject body = new JSONObject();`
body.put("test","test");

Webb webb = Webb.create();
webb.setBaseUri("http://localhost:8080/api");
Response<String> response = webb.post("/account/task").body(body).asString();
```
Server is a Wildfly 8 just responding with 401 and a json body.
If `connection.setFixedLengthStreamingMode` is set, the errorBody is null, if it is not set, errorBody contains the json string.

Looked at the jdk code (sun.net.www.protocol.http.HttpURLConnection), the problem is not in your code.
If the response is 401 (or 407) and the connection is in streaming mode (fixedContentLength != -1), the connection is immediately closed without reading the response.

**Comment by hgoebl** [comment]
Thanks for the deep investigation!

I'm not sure whether I understand it or at least I find it a bit strange. What has the streaming mode of the client (which should control how the upstream works) to do with the response? Does you Wildfly send 401 and a content without length? This would make sense not to download big chunks of data when authentication is missing.

Anyway, do you think we should close this issue?

**Comment by dreske** [comment]
Streaming mode is when (HttpURLConnection):
```java
public boolean streaming() {
        return this.fixedContentLength != -1 || this.fixedContentLengthLong != -1L || this.chunkLength != -1;
    }
```

If this is true, the connection would be closed without reading the response (on 401 and 407).

One workaround could be a flag (like `Request.noStreaming()`) which just prevents that you call `connection.setFixedLengthStreamingMode(requestBody.length);`

But yes, I think we can close it. :)
