### ISSUE TITLE
Would you please release an updated version for maven?

### ISSUE THREAD

**Issue by njuljsong** [hgoebl/DavidWebb#9]
Hi, 

I love your library and directly imported it in my maven project. 
Currently it is 1.1.0 version from Feb, 2014. 
I am trying to use the `retry` function but this version does not have this function.
Can you do another release when you have a chance?

Thanks!

**Comment by hgoebl** [comment]
I'll put it on my Prio-1 Todo-List...

**Comment by njuljsong** [comment]
Thank Mr. Heinrich You are awesome!

**Comment by hgoebl** [comment]
Sorry, I didn't manage to release a new version before my vacations. So please be patient, I'll be back in 2.5 weeks ...
In the meantime you could clone the repo and do `mvn -Dmaven.test.skip install` so you have it in your local repo or add the snapshot maven repository.

**Comment by njuljsong** [comment]
That's a great solution, too. 
Thanks!

**Comment by hgoebl** [comment]
david-web-1.2.0 released today
